modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
[[mods]] #mandatory
modId="serverstatistics" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Server Statistics" #mandatory
authors="Drathonix" #optional
description='''
Combines the statistics and advancements of ALL players into one global statistic system.
'''
[[dependencies.serverstatistics]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[40,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.serverstatistics]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
[[dependencies.serverstatistics]]
   modId="viciouscore"
   mandatory=true
   versionRange="[1.18.2-4.3.1,)"
   ordering="AFTER"
   side="BOTH"
